import type { Abi, Address } from "viem";
import tokenArtifact from "../../exports/token.json";
import obraArtifact from "../../exports/obra.json";
import marketArtifact from "../../exports/market.json";

/**
 * Single source of truth for contract ABIs + per-chain addresses.
 *
 * ABIs and addresses are read from `app/exports/*.json` — a synced copy of
 * the repo-root `/exports/*.json` (generated by the contracts package's
 * deploy/seed scripts; `token.json` originates from the sibling
 * staking-protocol repo). The copy exists because Vercel's CLI deploy
 * uploads only the `app/` subtree, which can't reach a sibling directory
 * one level up — see `npm run sync-exports` (re-run it after any contract
 * redeploy, before deploying the frontend). Every component must go
 * through `getContractAddress()` / the exported ABIs below instead of
 * hardcoding an address or ABI fragment locally.
 *
 * Cast to viem's `Abi` type: TypeScript's JSON-module inference widens each
 * entry's `type`/`stateMutability` fields to plain `string`, which doesn't
 * satisfy viem's discriminated-union `Abi` shape (`"function" | "event" |
 * ...`) on its own — wagmi/viem call sites that need the wider `Abi` type
 * (useReadContracts, getContractEvents) require this cast; simple
 * useReadContract/useWriteContract call sites work with either form.
 */
export const TOKEN_ABI = tokenArtifact.abi as Abi;
export const OBRA_ABI = obraArtifact.abi as Abi;
export const MARKET_ABI = marketArtifact.abi as Abi;

export const TOKEN_NAME: string = tokenArtifact.name;
export const TOKEN_SYMBOL: string = tokenArtifact.symbol;
export const TOKEN_DECIMALS: number = tokenArtifact.decimals;

export const COLLECTION_NAME: string = obraArtifact.name ?? "Obra";
export const COLLECTION_SYMBOL: string = obraArtifact.symbol ?? "OBRA";

type ContractKey = "token" | "obra" | "market";

const ADDRESS_BOOKS: Record<ContractKey, Record<string, string>> = {
  token: tokenArtifact.addresses,
  obra: obraArtifact.addresses,
  market: marketArtifact.addresses,
};

/**
 * Look up the deployed address of a contract on a given chain. Returns
 * `undefined` if that contract hasn't been deployed to this chain yet —
 * callers must treat this as a normal, expected "not yet deployed here"
 * state, not an error to throw on.
 */
export function getContractAddress(chainId: number | undefined, contract: ContractKey): Address | undefined {
  if (chainId === undefined) return undefined;
  const address = ADDRESS_BOOKS[contract][String(chainId)];
  return address ? (address as Address) : undefined;
}

/** Whether all three contracts (CHU, Obra, ObraMarket) are deployed on this chain. */
export function isProtocolDeployedOn(chainId: number | undefined): boolean {
  return (
    Boolean(getContractAddress(chainId, "token")) &&
    Boolean(getContractAddress(chainId, "obra")) &&
    Boolean(getContractAddress(chainId, "market"))
  );
}
